/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedEquipmentIndexRouteImport } from './routes/_authenticated/equipment.index'
import { Route as AuthenticatedAccessoriesIndexRouteImport } from './routes/_authenticated/accessories.index'
import { Route as AuthenticatedEquipmentIdRouteImport } from './routes/_authenticated/equipment.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin/usage'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAccessoriesIdRouteImport } from './routes/_authenticated/accessories.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipmentIndexRoute =
  AuthenticatedEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessoriesIndexRoute =
  AuthenticatedAccessoriesIndexRouteImport.update({
    id: '/accessories/',
    path: '/accessories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentIdRoute =
  AuthenticatedEquipmentIdRouteImport.update({
    id: '/equipment/$id',
    path: '/equipment/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccessoriesIdRoute =
  AuthenticatedAccessoriesIdRouteImport.update({
    id: '/accessories/$id',
    path: '/accessories/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/accessories/$id': typeof AuthenticatedAccessoriesIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/equipment/$id': typeof AuthenticatedEquipmentIdRoute
  '/accessories/': typeof AuthenticatedAccessoriesIndexRoute
  '/equipment/': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/accessories/$id': typeof AuthenticatedAccessoriesIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/equipment/$id': typeof AuthenticatedEquipmentIdRoute
  '/accessories': typeof AuthenticatedAccessoriesIndexRoute
  '/equipment': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/accessories/$id': typeof AuthenticatedAccessoriesIdRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/equipment/$id': typeof AuthenticatedEquipmentIdRoute
  '/_authenticated/accessories/': typeof AuthenticatedAccessoriesIndexRoute
  '/_authenticated/equipment/': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/accessories/$id'
    | '/admin/audit'
    | '/admin/import'
    | '/admin/usage'
    | '/admin/users'
    | '/equipment/$id'
    | '/accessories/'
    | '/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/accessories/$id'
    | '/admin/audit'
    | '/admin/import'
    | '/admin/usage'
    | '/admin/users'
    | '/equipment/$id'
    | '/accessories'
    | '/equipment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bookings'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/accessories/$id'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/usage'
    | '/_authenticated/admin/users'
    | '/_authenticated/equipment/$id'
    | '/_authenticated/accessories/'
    | '/_authenticated/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment/': {
      id: '/_authenticated/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AuthenticatedEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accessories/': {
      id: '/_authenticated/accessories/'
      path: '/accessories'
      fullPath: '/accessories/'
      preLoaderRoute: typeof AuthenticatedAccessoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment/$id': {
      id: '/_authenticated/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/equipment/$id'
      preLoaderRoute: typeof AuthenticatedEquipmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accessories/$id': {
      id: '/_authenticated/accessories/$id'
      path: '/accessories/$id'
      fullPath: '/accessories/$id'
      preLoaderRoute: typeof AuthenticatedAccessoriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedAccessoriesIdRoute: typeof AuthenticatedAccessoriesIdRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedEquipmentIdRoute: typeof AuthenticatedEquipmentIdRoute
  AuthenticatedAccessoriesIndexRoute: typeof AuthenticatedAccessoriesIndexRoute
  AuthenticatedEquipmentIndexRoute: typeof AuthenticatedEquipmentIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedAccessoriesIdRoute: AuthenticatedAccessoriesIdRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedEquipmentIdRoute: AuthenticatedEquipmentIdRoute,
  AuthenticatedAccessoriesIndexRoute: AuthenticatedAccessoriesIndexRoute,
  AuthenticatedEquipmentIndexRoute: AuthenticatedEquipmentIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
